# Generated by Django 4.0.4 on 2022-04-23 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Row created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Row updated at')),
                ('name', models.CharField(max_length=1024, unique=True, verbose_name='Client name')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Row created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Row updated at')),
                ('name', models.CharField(max_length=1024, unique=True, verbose_name='Organization name')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='billing.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Row created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Row updated at')),
                ('number', models.PositiveBigIntegerField(verbose_name='Bills number')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sum')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Bill date')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'unique_together': {('organization', 'number')},
            },
        ),
    ]
